default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: language_lesson_development

test:
  <<: *default
  database: language_lesson_test

production:
  <<: *default
  database: language_lesson_production
